<?php
define('Web_ID','1');
define('Web_Url','http://www.pan.com/');
define('Up_Dir','./video/data/');
define('Up_Ext','avi|wmv|mpeg|mp4|mov|mkv|flv|f4v|m4v|rmvb|rm|mpg');
define('Zm_Dir','./video/m3u8/');
define('Zm_Preset','veryfast');
define('Zm_Time',1);
define('Zm_Kbps','500k');
define('Zm_Size','');
define('Zm_Zm',0);
define('Zm_Sy',0);
define('Zm_Sylt','1:1');
define('Jpg_On',1);
define('Jpg_Num',9);
define('Jpg_Time',2);
define('Jpg_Size','350x240');
define('Api_Key','sdhnosadnosaidmsa');